### ISSUE TITLE
There is a big gap between the results of your  paper，what's the right params?

### ISSUE THREAD

**Issue by weidom** [emiliofidalgo/htmap#6]
I got this result of city_center dataset:
![31f319fea9440a612e717395849e3d5](https://user-images.githubusercontent.com/43192528/100426892-8c492e80-30cc-11eb-8bbe-59df492aa5b0.png)

params: I changed the param "loc_max_images = 100" ,others be default of this repo.

Is the "loc_max_images"  must be 500??   Or   Should I change other parameters?

**Comment by emiliofidalgo** [comment]
To be honest, I do not remember if these are the final params we used. Some hints:

- Initially, I will try the indicated default parameters to see if these are the correct ones.

- Do you use the images on the CC dataset as explained in the paper? I mean, joining left / right images and adapting the GC consequently?

**Comment by weidom** [comment]
Okay~  Thank you ~
