### ISSUE TITLE
opencv version

### ISSUE THREAD

**Issue by dearchonger** [emiliofidalgo/htmap#7]
I have tried to debug this code with opencv3.4.2 and opencv3.4.12, but they all failed.
Can you tell me which version of opencv is better?

**Comment by emiliofidalgo** [comment]
Could you please provide additional information about the errors you get to help you?

**Comment by dearchonger** [comment]
Thanks for your reply. I finally found out that flann conflicted with flann in opencv. The problem has been resolved, with opencv3.4.2.

**Comment by emiliofidalgo** [comment]
Perfect! Thanks!
